version: "3.9"
services:
  api:
    build:
      context: api
      target: dev
    ports:
      - 5000:3000
    volumes:
      - ./api:/api
    environment:
      NODE_ENV: development
      DEBUG: api:*
    depends_on:
      - redis
    container_name: api
  etl:
    image: jupyter/scipy-notebook
    ports:
      - 8888:8888
    volumes:
      - ./input:/home/jovyan/work/input
      - ./etl:/home/jovyan/work/etl
    container_name: etl
  redis:
    image: redislabs/rejson
    ports:
      - 6379:6379
    container_name: redis
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    container_name: mongoadmin
  postgres:
    image: postgres:alpine
  ui:
    build:
      context: ui
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./ui:/ui
      - /ui/node_modules
    # depends_on:
    #   - api
    container_name: ui

